version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "email-receiver-lambda"
resolve_s3 = false
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []